### ISSUE TITLE
Error packing JavaScript { message: 'Unexpected token punc, expected punc',

### ISSUE THREAD

**Issue by DennisNerush** [krasimir/assets-pack#3]
I have the following code that fails when I run the assetspacker
`module.exports = {

```
login(user, token) {
    localStorage.token = token;
    localStorage.user = user;
    this.onChange(true);
},
getToken() {
    return localStorage.token;
},
getUser() {
    return localStorage.user;
},
logout() {
    delete localStorage.token;
    delete localStorage.user;
    this.onChange(false);
},
loggedIn() {
    return !!localStorage.token;
},
onChange() { }
```

}
`

`[
    {
        "type": "js",
        "watch": "Clinet/js/",
        "pack": [ "Client/js" ],
        "output": "Client/js/scripts.js",
        "minify": true
    },
    {
        "type": "css",
        "watch": "Client/js",
        "pack": [ "Client/js" ],
        "output": "Client/js/styles.css",
        "minify": true
    }
]`

**Comment by krasimir** [comment]
The code that you have is following the new ES6 spec. You need a transpiler (like [babel](http://babeljs.io/) to get this working.
